fix: update getNodeVersion to getRuntimeNodeVersion
The function getNodeVersion was renamed to getRuntimeNodeVersion in @vercel/build-utils package (vercel/vercel#14600).

This change fixes the deployment error: Error: (0 , build_utils_1.getNodeVersion) is not a function

Fixes #594